version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:10.9-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql
      # - ./scripts:/scripts
      # - ./scripts/init.sql:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "55432:55432"

  api:
    image: maven:3.6-alpine
    volumes:
      - ./:/usr/src/mymaven
    ports:
      - 8080:8080
    depends_on:
      - db
    working_dir: /usr/src/mymaven
    command: bash -c "mvn compile && mvn package && mvn spring-boot:run"